#### 1. Import pandas library

In [1]:
import pandas as pd

#### 2. Import pymysql and sqlalchemy as you have learnt in the lesson of importing/exporting data

In [2]:
import pymysql
from sqlalchemy import create_engine

#### 3. Create a mysql engine to set the connection to the server. Check the connection details in [this link](https://relational.fit.cvut.cz/search?tableCount%5B%5D=0-10&tableCount%5B%5D=10-30&dataType%5B%5D=Numeric&databaseSize%5B%5D=KB&databaseSize%5B%5D=MB)

In [3]:

engine = create_engine('mysql+pymysql://guest:relational@relational.fit.cvut.cz')

#### 4. Import the users table

In [4]:

table = pd.read_sql_query('SELECT * FROM stats.users', engine)

#### 5. Rename Id column to userId

In [5]:
users = table.rename(columns={'Id':'userId'})
users.head()

,userId,Reputation,CreationDate,DisplayName,LastAccessDate,WebsiteUrl,Location,AboutMe,Views,UpVotes,DownVotes,AccountId,Age,ProfileImageUrl
0,-1,1,2010-07-19 06:55:26,Community,2010-07-19 06:55:26,http://meta.stackexchange.com/,on the server farm,"<p>Hi, I'm not really a person.</p>\n\n<p>I'm ...",0,5007,1920,-1,NaN,None
1,2,101,2010-07-19 14:01:36,Geoff Dalgas,2013-11-12 22:07:23,http://stackoverflow.com,"Corvallis, OR",<p>Developer on the StackOverflow team. Find ...,25,3,0,2,37.0,None
2,3,101,2010-07-19 15:34:50,Jarrod Dixon,2014-08-08 06:42:58,http://stackoverflow.com,"New York, NY","<p><a href=""http://blog.stackoverflow.com/2009...",22,19,0,3,35.0,None
3,4,101,2010-07-19 19:03:27,Emmett,2014-01-02 09:31:02,http://minesweeperonline.com,"San Francisco, CA",<p>currently at a startup in SF</p>\n\n<p>form...,11,0,0,1998,28.0,http://i.stack.imgur.com/d1oHX.jpg
4,5,6792,2010-07-19 19:03:57,Shane,2014-08-13 00:23:47,http://www.statalgo.com,"New York, NY",<p>Quantitative researcher focusing on statist...,1145,662,5,54503,35.0,None

#### 6. Import the posts table.

In [6]:
tableb = pd.read_sql_query('SELECT * FROM stats.posts', engine)

#### 7. Rename Id column to postId and OwnerUserId to userId

In [17]:
posts = tableb.rename(columns={'Id':'postId','OwnerUserId':'userId'})

#### 8. Define new dataframes for users and posts with the following selected columns:
    **users columns**: userId, Reputation,Views,UpVotes,DownVotes
    **posts columns**: postId, Score,userID,ViewCount,CommentCount

In [18]:
users_columns = ['userId','Reputation','Views','UpVotes',
                'DownVotes']
posts_columns = ["postId", "Score","userId","ViewCount","CommentCount"]

#### 8. Merge both dataframes, users and posts. 
You will need to make a [merge](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.merge.html) of posts and users dataframes.

In [20]:
merges= pd.merge(posts, users, on='userId')
#users
#posts
merges

,postId,PostTypeId,AcceptedAnswerId,CreaionDate,Score,ViewCount,Body,userId,LasActivityDate,Title,...,LastAccessDate,WebsiteUrl,Location,AboutMe,Views,UpVotes,DownVotes,AccountId,Age,ProfileImageUrl
0,1,1,15.0,2010-07-19 19:12:12,23,1278.0,<p>How should I elicit prior distributions fro...,8.0,2010-09-15 21:08:26,Eliciting priors from experts,...,2014-09-09 21:15:08,http://www.mas.ncl.ac.uk/~ncsg3/,"Newcastle, United Kingdom",<p>I'm a statistics lecturer at Newcastle Univ...,1089,604,25,70002,36.0,None
1,16,2,NaN,2010-07-19 19:22:31,16,NaN,<p>Two projects spring to mind:</p>\n\n<ol>\n<...,8.0,2010-07-19 20:43:02,None,...,2014-09-09 21:15:08,http://www.mas.ncl.ac.uk/~ncsg3/,"Newcastle, United Kingdom",<p>I'm a statistics lecturer at Newcastle Univ...,1089,604,25,70002,36.0,None
2,36,1,NaN,2010-07-19 19:31:47,41,67396.0,"<p>There is an old saying: ""Correlation does n...",8.0,2014-05-23 06:31:12,Examples for teaching: Correlation does not me...,...,2014-09-09 21:15:08,http://www.mas.ncl.ac.uk/~ncsg3/,"Newcastle, United Kingdom",<p>I'm a statistics lecturer at Newcastle Univ...,1089,604,25,70002,36.0,None
3,65,2,NaN,2010-07-19 19:46:11,14,NaN,<p>The first formula is the <em>population</em...,8.0,2010-07-19 20:44:53,None,...,2014-09-09 21:15:08,http://www.mas.ncl.ac.uk/~ncsg3/,"Newcastle, United Kingdom",<p>I'm a statistics lecturer at Newcastle Univ...,1089,604,25,70002,36.0,None
4,78,2,NaN,2010-07-19 19:54:38,33,NaN,<p>You tend to use the covariance matrix when ...,8.0,2010-11-06 21:56:17,None,...,2014-09-09 21:15:08,http://www.mas.ncl.ac.uk/~ncsg3/,"Newcastle, United Kingdom",<p>I'm a statistics lecturer at Newcastle Univ...,1089,604,25,70002,36.0,None
5,111,2,NaN,2010-07-19 20:41:24,8,NaN,"<p>In R, the default setting for random number...",8.0,2010-07-19 20:41:24,None,...,2014-09-09 21:15:08,http://www.mas.ncl.ac.uk/~ncsg3/,"Newcastle, United Kingdom",<p>I'm a statistics lecturer at Newcastle Univ...,1089,604,25,70002,36.0,None
6,114,1,NaN,2010-07-19 21:00:53,30,1220.0,<p>What statistical research blogs would you r...,8.0,2014-06-02 12:33:11,What statistical blogs would you recommend?,...,2014-09-09 21:15:08,http://www.mas.ncl.ac.uk/~ncsg3/,"Newcastle, United Kingdom",<p>I'm a statistics lecturer at Newcastle Univ...,1089,604,25,70002,36.0,None
7,129,2,NaN,2010-07-19 21:24:58,4,NaN,"<p>I quite like <a href=""http://rads.stackover...",8.0,2010-10-05 13:56:15,None,...,2014-09-09 21:15:08,http://www.mas.ncl.ac.uk/~ncsg3/,"Newcastle, United Kingdom",<p>I'm a statistics lecturer at Newcastle Univ...,1089,604,25,70002,36.0,None
8,142,2,NaN,2010-07-19 21:42:57,5,NaN,"<p>After you learn the basics, I find the foll...",8.0,2010-07-19 21:42:57,None,...,2014-09-09 21:15:08,http://www.mas.ncl.ac.uk/~ncsg3/,"Newcastle, United Kingdom",<p>I'm a statistics lecturer at Newcastle Univ...,1089,604,25,70002,36.0,None
9,168,1,179.0,2010-07-19 23:26:44,17,1022.0,<p>For univariate kernel density estimators (K...,8.0,2011-03-02 12:11:19,Choosing a bandwidth for kernel density estima...,...,2014-09-09 21:15:08,http://www.mas.ncl.ac.uk/~ncsg3/,"Newcastle, United Kingdom",<p>I'm a statistics lecturer at Newcastle Univ...,1089,604,25,70002,36.0,None
10,170,1,174.0,2010-07-19 23:29:54,56,7733.0,<p>Are there any free statistical textbooks av...,8.0,2014-06-20 00:16:54,Free statistical textbooks,...,2014-09-09 21:15:08,http://www.mas.ncl.ac.uk/~ncsg3/,"Newcastle, United Kingdom",<p>I'm a statistics lecturer at Newcastle Univ...,1089,604,25,70002,36.0,None
11,254,2,NaN,2010-07-20 09:30:18,4,NaN,<p>I think if I understand your description co...,8.0,2010-07-20 10:50:24,None,...,2014-09-09 21:15:08,http://www.mas.ncl.ac.uk/~ncsg3/,"Newcastle, United Kingdom",<p>I'm a statistics lecturer at Newcastle Univ...,1089,604,25,70002,36.0,None
12,262,2,NaN,2010-07-20 09:50:45,13,NaN,<p>The easiest way is to use R </p>\n\n<p>Use ...,8.0,2010-07-20 14:48:45,None,...,2014-09-09 21:15:08,http://www.mas.ncl.ac.uk/~ncsg3/,"Newcastle, United Kingdom",<p>I'm a statistics lecturer at Newcastle Univ...,1089,604,25,70002,36.0,None
13,271,2,NaN,2010-07-20 11:10:42,7,NaN,"<p>If I understand your question correctly, yo...",8.0,2013-07-17 02:30:07,None,...,2014-09-09 21:15:08,http://www.mas.ncl.ac.uk/~ncsg3/,"Newcastle, United Kingdom",<p>I'm a statistics lecturer at Newcastle Univ...,1089,604,25,70002,36.0,None
14,301,2,NaN,2010-07-20 13:22:40,6,NaN,<p>You tend to take logs of the data when ther...,8.0,2010-07-20 13:22:40,None,...,2014-09-09 21:15:08,http://www.mas.ncl.ac.uk/~ncsg3/,"Newcastle, United Kingdom",<p>I'm a statistics lecturer at Newcastle Univ...,1089,604,25,70002,36.0,None
15,352,2,NaN,2010-07-20 21:18:45,1,NaN,"<p>I've never had to do this, so this is just ...",8.0,2010-07-21 15:29:25,None,...,2014-09-09 21:15:08,http://www.mas.ncl.ac.uk/~ncsg3/,"Newcastle, United Kingdom",<p>I'm a statistics lecturer at Newcastle Univ...,1089,604,25,70002,36.0,None
16,356,2,NaN,2010-07-20 22:31:45,2,NaN,"<p>To fit the model you can use <a href=""http:...",8.0,2010-07-20 22:31:45,None,...,2014-09-09 21:15:08,http://www.mas.ncl.ac.uk/~ncsg3/,"Newcastle, United Kingdom",<p>I'm a statistics lecturer at Newcastle Univ...,1089,604,25,70002,36.0,None
17,397,2,NaN,2010-07-21 11:11:47,5,NaN,"<p>Just to add a bit to honk's answer, the <a ...",8.0,2010-09-28 22:20:14,None,...,2014-09-09 21:15:08,http://www.mas.ncl.ac.uk/~ncsg3/,"Newcastle, United Kingdom",<p>I'm a statistics lecturer at Newcastle Univ...,1089,604,25,70002,36.0,None
18,412,2,NaN,2010-07-21 13:40:02,4,NaN,<p>I think you need look at statistical <a hre...,8.0,2010-07-21 13:40:02,None,...,2014-09-09 21:15:08,http://www.mas.ncl.ac.uk/~ncsg3/,"Newcastle, United Kingdom",<p>I'm a statistics lecturer at Newcastle Univ...,1089,604,25,70002,36.0,None
19,432,2,NaN,2010-07-21 15:38:46,96,NaN,<p>My favourite Dilbert cartoon:</p>\n\n<p><im...,8.0,2010-07-21 15:38:46,None,...,2014-09-09 21:15:08,http://www.mas.ncl.ac.uk/~ncsg3/,"Newcastle, United Kingdom",<p>I'm a statistics lecturer at Newcastle Univ...,1089,604,25,70002,36.0,None
20,845,2,NaN,2010-07-27 19:02:09,5,NaN,<p>If you want to go down the non-parametric r...,8.0,2010-07-28 00:08:20,None,...,2014-09-09 21:15:08,http://www.mas.ncl.ac.uk/~ncsg3/,"Newcastle, United Kingdom",<p>I'm a statistics lecturer at Newcastle Univ...,1089,604,25,70002,36.0,None
21,851,2,NaN,2010-07-27 19:34:06,4,NaN,<p>The Fisher Snedecor distribution is another...,8.0,2010-07-27 19:34:06,None,...,2014-09-09 21:15:08,http://www.mas.ncl.ac.uk/~ncsg3/,"Newcastle, United Kingdom",<p>I'm a statistics lecturer at Newcastle Univ...,1089,604,25,70002,36.0,None
22,855,2,NaN,2010-07-27 20:05:20,1,NaN,"<p>I thought this was too obvious, until I saw...",8.0,2010-07-27 20:05:20,None,...,2014-09-09 21:15:08,http://www.mas.ncl.ac.uk/~ncsg3/,"Newcastle, United Kingdom",<p>I'm a statistics lecturer at Newcastle Univ...,1089,604,25,70002,36.0,None
23,895,2,NaN,2010-07-28 12:50:26,2,NaN,<p>I'm finding it rather tricky to see what yo...,8.0,2010-07-28 12:50:26,None,...,2014-09-09 21:15:08,http://www.mas.ncl.ac.uk/~ncsg3/,"Newcastle, United Kingdom",<p>I'm a statistics lecturer at Newcastle Univ...,1089,604,25,70002,36.0,None
24,975,2,NaN,2010-07-29 12:44:50,2,NaN,"<p>Another good podcast is <a href=""http://www...",8.0,2010-07-29 12:44:50,None,...,2014-09-09 21:15:08,http://www.mas.ncl.ac.uk/~ncsg3/,"Newcastle, United Kingdom",<p>I'm a statistics lecturer at Newcastle Univ...,1089,604,25,70002,36.0,None
25,978,2,NaN,2010-07-29 13:51:07,3,NaN,"<p>I think you should look at <a href=""http://...",8.0,2010-07-29 13:51:07,None,...,2014-09-09 21:15:08,http://www.mas.ncl.ac.uk/~ncsg3/,"Newcastle, United Kingdom",<p>I'm a statistics lecturer at Newcastle Univ...,1089,604,25,70002,36.0,None
26,981,2,NaN,2010-07-29 14:15:09,6,NaN,<p>You have two problems: too many points and ...,8.0,2010-07-30 11:00:12,None,...,2014-09-09 21:15:08,http://www.mas.ncl.ac.uk/~ncsg3/,"Newcastle, United Kingdom",<p>I'm a statistics lecturer at Newcastle Univ...,1089,604,25,70002,36.0,None
27,1010,2,NaN,2010-07-29 21:20:25,8,NaN,"<p>If I understand correctly, then you can jus...",8.0,2010-07-29 21:20:25,None,...,2014-09-09 21:15:08,http://www.mas.ncl.ac.uk/~ncsg3/,"Newcastle, United Kingdom",<p>I'm a statistics lecturer at Newcastle Univ...,1089,604,25,70002,36.0,None
28,1131,2,NaN,2010-08-02 18:52:56,4,NaN,<blockquote>\n <p>Save money</p>\n</blockquot...,8.0,2010-08-02 18:52:56,None,...,2014-09-09 21:15:08,http://www.mas.ncl.ac.uk/~ncsg3/,"Newcastle, United Kingdom",<p>I'm a statistics lecturer at Newcastle Univ...,1089,604,25,70002,36.0,None
29,1132,2,NaN,2010-08-02 19:16:14,4,NaN,<blockquote>\n <p>For fun!</p>\n</blockquote>...,8.0,2010-08-02 19:16:14,None,...,2014-09-09 21:15:08,http://www.mas.ncl.ac.uk/~ncsg3/,"Newcastle, United Kingdom",<p>I'm a statistics lecturer at Newcastle Univ...,1089,604,25,70002,36.0,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90554,115285,1,NaN,2014-09-12 16:54:35,0,22.0,<p>My response variable is a questionnaire sco...,55697.0,2014-09-12 16:54:35,Problems with bounded response variable,...,2014-09-13 09:42:26,None,None,None,0,0,0,5022491,NaN,https://www.gravatar.com/avatar/c7881c8ba2a5c8...
90555,115287,1,NaN,2014-09-12 17:26:43,1,23.0,<p>I failed to pass my regression analysis cou...,55699.0,2014-09-12 17:41:06,What method should I use to analyze data?,...,2014-09-13 19:39:55,None,None,None,0,0,0,5022766,NaN,None
90556,115291,1,NaN,2014-09-12 18:13:44,5,29.0,<p>I'm wondering what distribution results in ...,55702.0,2014-09-12 18:13:44,What distribution results in adding two Pareto...,...,2014-09-12 18:13:44,None,None,None,1,0,0,5022953,NaN,None
90557,115292,2,NaN,2014-09-12 18:14:53,2,NaN,<p>I don't think that a list with pros and con...,48622.0,2014-09-12 18:41:20,None,...,2014-09-12 19:07:50,None,None,None,0,1,0,3399912,NaN,https://www.gravatar.com/avatar/24410e924c0e7e...
90558,115295,2,NaN,2014-09-12 18:46:24,0,NaN,<p>You want to know what the probability is th...,53248.0,2014-09-12 18:46:24,None,...,2014-09-12 18:40:53,None,None,None,0,0,0,93793,NaN,https://www.gravatar.com/avatar/49594bd3f61e3c...
90559,115298,1,NaN,2014-09-12 20:23:53,1,8.0,<p>I have a web crawler and i want to be able ...,54582.0,2014-09-12 20:23:53,Supervised learning algorithm that can be easi...,...,2014-09-12 20:14:04,None,Brazil,None,0,0,0,3970982,23.0,https://www.gravatar.com/avatar/ef2c27d8b4dc9c...
90560,115312,1,NaN,2014-09-12 22:23:12,0,6.0,<p>I am trying to compare the results of two m...,55709.0,2014-09-12 22:23:12,Univariate fixed effect Vs Multivariate model ...,...,2014-09-12 22:21:49,None,None,None,0,0,0,5023747,NaN,https://www.gravatar.com/avatar/2d103e73ede4cf...
90561,115313,1,NaN,2014-09-12 22:49:11,0,18.0,<p>I'm having trouble proving a N.N.D matrix h...,55710.0,2014-09-12 23:43:58,A non-negative definate matrix has a non-negat...,...,2014-09-12 23:42:48,None,None,None,0,0,0,3768680,NaN,https://www.gravatar.com/avatar/34f361d60f4a9c...
90562,115315,1,NaN,2014-09-13 00:10:52,1,36.0,<p>Sorry if this type of question is not koshe...,55713.0,2014-09-13 02:16:39,What distribution family would best fit this g...,...,2014-09-13 01:05:33,None,None,None,0,0,0,2346002,NaN,https://www.gravatar.com/avatar/d3ff258f07d607...
90563,115316,1,NaN,2014-09-13 00:31:44,1,20.0,<p>I came across a formula presented in a fina...,55714.0,2014-09-13 00:57:34,Unknown formula,...,2014-09-13 08:31:02,None,None,None,0,0,0,5024006,NaN,None
90564,115321,1,NaN,2014-09-13 02:46:40,1,9.0,<p>I've collected data on accuracy of recognit...,55715.0,2014-09-13 08:34:34,"Transforming data with a limited range (0,1,2)...",...,2014-09-13 02:46:40,None,None,None,0,0,0,5024218,NaN,None
90565,115327,1,NaN,2014-09-13 07:12:49,1,25.0,<p>I was evaluating a research paper in which ...,55718.0,2014-09-13 08:45:24,If one group has 23 participants and the secon...,...,2014-09-13 07:12:49,None,None,None,0,0,0,5024818,NaN,None
90566,115328,1,NaN,2014-09-13 07:19:09,0,10.0,<p>Good morning scholars. Please am fitting a ...,55719.0,2014-09-13 07:19:09,"model specification for SARIMA order (2,1,2)x(...",...,2014-09-13 08:03:19,None,None,None,1,0,0,5024833,NaN,None
90567,115331,1,NaN,2014-09-13 08:02:51,0,12.0,<p>I am a complete beginner at using R but hav...,55720.0,2014-09-13 08:02:51,Importing tables from MS access into R,...,2014-09-13 08:00:08,None,None,None,0,0,0,5024897,NaN,https://www.gravatar.com/avatar/2bc72d263cc5a8...
90568,115335,1,NaN,2014-09-13 10:09:50,3,19.0,"<p>I have a set of objects, each of which can ...",55724.0,2014-09-13 10:09:50,Visualising changes in many-to-one (directiona...,...,2014-09-13 10:05:17,None,None,<p>I'm a self-taught programmer and linux powe...,1,0,0,3620179,NaN,https://www.gravatar.com/avatar/1f8dbbc900087e...
90569,115338,2,NaN,2014-09-13 11:04:54,0,NaN,<p>All items are not solved fully correctly in...,55729.0,2014-09-13 11:04:54,None,...,2014-09-13 12:15:21,None,None,None,1,0,0,5025362,NaN,None
90570,115340,1,NaN,2014-09-13 12:01:38,0,18.0,<p>I am working on decision trees for the firs...,55730.0,2014-09-13 12:01:38,Query on Quants,...,2014-09-13 12:01:38,None,None,None,0,0,0,5025477,NaN,None
90571,115348,1,NaN,2014-09-13 15:17:03,0,18.0,"<p>In the game of Bridge, 52 cards are distrub...",55564.0,2014-09-13 16:25:32,Please help me interpret this goodness of fit ...,...,2014-09-13 21:18:59,http://www.bridgemate.com,Netherlands,<p>MCTS in Windows Presentation Foundation sin...,0,1,0,37896,51.0,https://www.gravatar.com/avatar/176fcb7e1c5e57...
90572,115350,1,NaN,2014-09-13 15:26:01,0,3.0,<p>How do we specify negative costs in rpart? ...,55731.0,2014-09-13 15:26:01,Specifying negative costs (benefits) in rpart'...,...,2014-09-13 20:51:55,None,None,None,0,0,0,5025991,NaN,None
90573,115351,1,NaN,2014-09-13 15:32:18,1,9.0,<p>If one is conducting a survey in which all ...,7331.0,2014-09-13 15:43:23,Sampling frame of a voluntary survey,...,2014-09-13 15:27:00,None,"New York, NY",<p>A Columbia Statistics Major.</p>\n,2,0,0,1034490,NaN,None
90574,115352,1,NaN,2014-09-13 15:56:55,0,16.0,"<p>For example, I was looking at <a href=""http...",55734.0,2014-09-13 16:15:30,Is there a way to estimate the distribution fr...,...,2014-09-13 15:56:55,None,None,None,0,0,0,5026094,NaN,None
90575,115356,1,NaN,2014-09-13 16:34:58,1,15.0,<p>I'm a beginner in statistics and I have to ...,55733.0,2014-09-13 20:45:45,"How to interpret glmer results (variance, corr...",...,2014-09-13 23:57:22,None,None,None,1,0,0,5026082,NaN,https://www.gravatar.com/avatar/d9b1e7660eb8ed...
90576,115360,1,NaN,2014-09-13 18:06:50,2,40.0,<p>Is Student's t test a Wald test?</p>\n\n<p>...,55738.0,2014-09-13 18:06:50,Is Student's t test a Wald test?,...,2014-09-14 01:34:01,None,None,None,0,0,0,5026468,NaN,None
90577,115361,1,NaN,2014-09-13 18:36:36,0,12.0,"<p>Given the biometric match scores, I am requ...",55383.0,2014-09-13 18:36:36,Plotting of density estimates in matlab,...,2014-09-13 20:16:19,None,None,<p>Please delete me</p>\n,0,0,0,3527597,NaN,https://www.gravatar.com/avatar/738b86a6f3ec90...
90578,115364,1,NaN,2014-09-13 19:50:17,0,11.0,<p>I'm trying to find the most similar sample ...,52858.0,2014-09-13 21:30:41,In search of a proper similarity function,...,2014-09-13 21:26:40,None,None,None,2,1,0,103108,NaN,https://www.gravatar.com/avatar/c7152460e37374...
90579,115366,1,NaN,2014-09-13 20:36:55,1,17.0,<p>Does any standard statistical software like...,55742.0,2014-09-13 23:18:30,Missing data analysis software,...,2014-09-13 22:04:00,None,None,None,0,0,0,5026843,NaN,None
90580,115370,1,NaN,2014-09-13 21:39:30,1,13.0,<p>im analyzing an article for my studies with...,55744.0,2014-09-13 21:39:30,Poisson regression,...,2014-09-13 21:39:30,None,None,None,1,0,0,5026998,NaN,None
90581,115371,1,NaN,2014-09-13 21:55:39,0,19.0,<p>I am trying to estimate the school effects ...,35801.0,2014-09-13 23:15:00,Estimation of school effects using xtmixed (in...,...,2014-09-14 01:52:01,None,None,None,1,0,0,3525646,NaN,https://www.gravatar.com/avatar/?s=128&d=ident...
90582,115375,1,NaN,2014-09-13 23:46:05,0,9.0,<p>Assume a classification problem where there...,49365.0,2014-09-14 02:09:23,Detecting a consistent pattern in a dataset vi...,...,2014-09-13 23:55:06,http://uk.linkedin.com/in/leonidasphd/,London,<p>Front-end and back-end developer on real ti...,0,0,0,4641129,NaN,http://graph.facebook.com/651010106/picture?ty...
90583,115376,1,NaN,2014-09-14 01:27:54,1,5.0,<p>My goal is to create a formula that can giv...,55746.0,2014-09-14 01:40:55,How to project video viewcount based on histor...,...,2014-09-14 02:05:17,None,None,"<p>Stats noobie, product, marketing &amp; medi...",1,0,0,976289,NaN,https://www.gravatar.com/avatar/6d9e9fa6b783a3...

#### 9. How many missing values do you have in your merged dataframe? On which columns?

In [30]:
null_cols = merges.isnull().sum()
null_cols.head()

postId                  0
PostTypeId              0
AcceptedAnswerId    76021
CreaionDate             0
Score                   0
dtype: int64

#### 10. You will need to make something with missing values.  Will you clean or filling them? Explain. 
**Remember** to check the results of your code before passing to the next step

In [31]:
merges.info
merges.describe
drop_cols = list(null_cols[null_cols > 10000].index)
remove = merges.drop(drop_cols, axis=1)

#### 11. Adjust the data types in order to avoid future issues. Which ones should be changed?

In [32]:
merges.describe
null_cols = merges.isnull().sum()
null_cols.head()

postId                  0
PostTypeId              0
AcceptedAnswerId    76021
CreaionDate             0
Score                   0
dtype: int64

#### Bonus: Identify extreme values in your merged dataframe as you have learned in class, create a dataframe called outliers with the same columns as our data set and calculate the bounds. The values of the outliers dataframe will be the values of the merged_df that fall outside that bounds. You will need to save your outliers dataframe to a csv file on your-code folder.