In [1]:
from pymongo import MongoClient
import pandas as pd
from pandas.io.json import json_normalize

In [2]:
def mongo(sector,year):
    client = MongoClient('localhost', 27017)

    db = client['companies']
    comg = db.companies.find({"$and":[{"category_code":sector},{'founded_year':{'$gte':year}},{'offices.latitude':{'$exists':True}},{'offices.longitude':{'$exists':True}},{'deadpooled_year':None}]},{'name':1, 'founded_year': 1, '_id': 0, 'number_of_employees':1,
                                'offices.latitude':1, 'offices.longitude':1, 'funding_rounds.raised_amount':1, 
      'funding_rounds.raised_currency_code':1, 'category_code':1, 'total_money_raised':1})
    
    co=pd.DataFrame(comg)
    return co

- VISUALIZATION PROJECT Geospatial Business Intelligence (BI)
    * Make a geospartial analysis of the `companies` dataset
    * Things you know:
        - You have a software company with 50 employees
        - The company creates video games
        - Roles in your company: 20 developers, 20 Designers/Creatieves/UX/UI and 10 executives/managers
    * Do an analysis about placing the new company offices in the best environment based on the following criteria:
        - There should be software engineers working around
        - The surroundings must have a good ratio of big companies vs startups
        - Ensure you have in your surroundings companies that cover the interests of your team
        - Avoid old companies, prefer recently created ones

In [3]:
#pa ver la tabla
#client = MongoClient ('localhost', 27017)

#db = client.companies
#comg=db.companies.find({"$and":[{"category_code":"games_video"},{'founded_year':{'$gte':2003}},{'number_of_employees':{'$gte':5}},{'offices.latitude':{'$exists':True}},{'offices.longitude':{'$exists':True}},{'deadpooled_year':None}]},{'name':1, 'founded_year': 1, '_id': 0, 'number_of_employees':1,
                                 #'offices.latitude':1, 'offices.longitude':1, 'funding_rounds.raised_amount':1, 
                                 #'funding_rounds.raised_currency_code':1, 'category_code':1, 'total_money_raised':1})
#co=pd.DataFrame(comg)
#co.head()

In [4]:

#set(co)

In [5]:

def getlat(coor): 
    try: 
        return coor[0]['latitude']
    except:
        return None

   
def getlong(coor): 
    try: 
        return coor[0]['longitude']
    except:
        return None

   
def col_latlong(comp):   
    comp['latitude'] = comp['offices'].apply(getlat)
    comp['longitude'] = comp['offices'].apply(getlong)
    return comp

def getraised(funding): 
    try: 
        return funding[0]['raised_amount']
    except:
        return None
   
def getcurrency(funding): 
    try: 
        return funding[0]['raised_currency_code']
    except:
        return None

   
def col_funding(funding):   
    funding['raised_amount'] = funding['funding_rounds'].apply(getraised)
    funding['raised_currency_code'] = funding['funding_rounds'].apply(getcurrency)
    return funding

def col_drop(data):
    data = data.drop(['offices', 'funding_rounds'], axis=1)
    return data

In [6]:
#co.head()

In [7]:
companies = mongo("games_video",2008)
display(companies.head())
datalocation = col_latlong(companies)

datalocfund = col_funding(datalocation)
clean_companies = col_drop(datalocfund)
clean_companies.head()

,category_code,founded_year,funding_rounds,name,number_of_employees,offices,total_money_raised
0,games_video,2008,"[{'raised_amount': None, 'raised_currency_code...",YouBeQB,8.0,"[{'latitude': 47.597965, 'longitude': -122.151...",$0
1,games_video,2008,"[{'raised_amount': 4050000, 'raised_currency_c...",Crunchyroll,50.0,"[{'latitude': 37.781265, 'longitude': -122.393...",$4.8M
2,games_video,2009,[],alluc,7.0,"[{'latitude': 53.707739, 'longitude': 10.023246}]",$0
3,games_video,2008,[],Fancast,NaN,"[{'latitude': None, 'longitude': None}]",$0
4,games_video,2008,"[{'raised_amount': None, 'raised_currency_code...",WonderHowTo,12.0,"[{'latitude': 34.031764, 'longitude': -118.461...",$0

,category_code,founded_year,name,number_of_employees,total_money_raised,latitude,longitude,raised_amount,raised_currency_code
0,games_video,2008,YouBeQB,8.0,$0,47.597965,-122.151158,NaN,None
1,games_video,2008,Crunchyroll,50.0,$4.8M,37.781265,-122.393229,4050000.0,USD
2,games_video,2009,alluc,7.0,$0,53.707739,10.023246,NaN,None
3,games_video,2008,Fancast,NaN,$0,NaN,NaN,NaN,None
4,games_video,2008,WonderHowTo,12.0,$0,34.031764,-118.461884,NaN,None

In [9]:
clean_companies.fillna(0)

,category_code,founded_year,name,number_of_employees,total_money_raised,latitude,longitude,raised_amount,raised_currency_code
0,games_video,2008,YouBeQB,8.0,$0,47.597965,-122.151158,0.0,0
1,games_video,2008,Crunchyroll,50.0,$4.8M,37.781265,-122.393229,4050000.0,USD
2,games_video,2009,alluc,7.0,$0,53.707739,10.023246,0.0,0
3,games_video,2008,Fancast,0.0,$0,0.000000,0.000000,0.0,0
4,games_video,2008,WonderHowTo,12.0,$0,34.031764,-118.461884,0.0,0
5,games_video,2008,Triptuber,2.0,$0,25.294800,51.508200,0.0,0
6,games_video,2008,Volo Media,0.0,$0,0.000000,0.000000,0.0,0
7,games_video,2011,Social Gaming Network,100.0,$17.1M,37.446823,-122.161523,15000000.0,USD
8,games_video,2008,Newsclipper,0.0,$0,37.269175,-119.306607,0.0,0
9,games_video,2008,CineGoGo,2.0,$0,37.534317,-122.294847,0.0,0
10,games_video,2008,politicsultra,0.0,$0,47.693994,-122.349701,0.0,0
11,games_video,2009,Crootpad,2.0,$0,42.091078,-88.288749,0.0,0
12,games_video,2009,Handipoints,0.0,$800k,37.772323,-122.214897,250000.0,USD
13,games_video,2008,Clipta,16.0,$0,37.379372,-122.012440,0.0,0
14,games_video,2008,tunesBag,0.0,$0,0.000000,0.000000,0.0,0
15,games_video,2008,Episodic,6.0,$0,37.269175,-119.306607,0.0,0
16,games_video,2008,Rosterbot,0.0,$0,49.276778,-123.121062,0.0,0
17,games_video,2008,stickychicken,2.0,$0,37.775196,-122.419204,0.0,0
18,games_video,2008,AudioMicro,10.0,$1.25M,34.153588,-118.422495,750000.0,USD
19,games_video,2008,Guitarati,0.0,$0,39.739300,-89.266508,0.0,0
20,games_video,2008,Teet,0.0,$0,56.879635,24.603189,0.0,0
21,games_video,2008,YUPPTV,70.0,$0,17.415429,78.434422,0.0,0
22,games_video,2008,Sutros,3.0,$0,37.756922,-122.420870,0.0,0
23,games_video,2008,Serious Business,22.0,$4M,37.789321,-122.401362,4000000.0,USD
24,games_video,2008,twit+,1.0,$0,52.472029,-0.698361,0.0,0
25,games_video,2008,Rekatu,5.0,$0,32.240301,-110.958319,0.0,0
26,games_video,2008,Jinni,35.0,$8.1M,32.055400,34.759500,1500000.0,USD
27,games_video,2008,RouteNote,0.0,$0,50.231464,-5.236903,0.0,0
28,games_video,2011,Fuzz,6.0,$0,37.760524,-122.387799,0.0,0
29,games_video,2008,Wuapi,0.0,$0,41.387917,2.169919,0.0,0
...,...,...,...,...,...,...,...,...,...
145,games_video,2008,Silvatar Media,4.0,$0,34.103635,-118.293316,0.0,0
146,games_video,2008,Sloshspot,0.0,$0,37.320052,-121.877636,0.0,0
147,games_video,2009,Gameleaper,1.0,$0,32.827005,-96.843222,0.0,0
148,games_video,2011,Hayen Company,1.0,$0,34.019114,-81.004871,0.0,0
149,games_video,2009,BIT TV,10.0,$0,45.488419,-122.642156,0.0,0
150,games_video,2008,Owngig,8.0,$0,39.396150,22.763030,0.0,0
151,games_video,2008,"Dance Channel TV, Inc",5.0,$0,34.165880,-118.363726,0.0,0
152,games_video,2008,Playdom,0.0,$76M,37.393536,-122.076747,43000000.0,USD
153,games_video,2010,Flixxy,0.0,$0,27.972364,-82.800333,0.0,0
154,games_video,2009,Velvet View,0.0,$0,0.000000,0.000000,0.0,0
155,games_video,2008,HashCube,5.0,$0,12.910491,77.585717,0.0,USD
156,games_video,2008,Funji,0.0,$0,0.000000,0.000000,0.0,0
157,games_video,2011,Molecube,6.0,$0,0.000000,0.000000,0.0,0
158,games_video,2009,Undead Code Studios,5.0,$0,40.636710,-3.998048,0.0,0
159,games_video,2010,ekidnaworld,10.0,$0,-27.457486,153.033686,0.0,0
160,games_video,2009,scoyo,13.0,$0,53.562270,9.949014,0.0,0
161,games_video,2009,Meuzer,3.0,$0,37.320052,-121.877636,0.0,0
162,games_video,2008,Mudlark,12.0,$0,0.000000,0.000000,0.0,0
163,games_video,2008,EPIX,0.0,$0,0.000000,0.000000,0.0,0
164,games_video,2009,Vevo,0.0,$0,0.000000,0.000000,0.0,0
165,games_video,2008,Sticher,0.0,$100k,37.809338,-122.416606,100000.0,USD
166,games_video,2008,BetKlub,3.0,€91k,48.878761,2.363917,91000.0,EUR
167,games_video,2009,Tour Volume,2.0,$0,0.000000,0.000000,0.0,0
168,games_video,2008,Multiso Multimedia Solutions,1.0,$0,46.234740,15.259106,0.0,0
169,games_video,2009,SPOTI,6.0,$0,0.000000,0.000000,0.0,0
170,games_video,2008,Antix Labs,0.0,$3M,0.000000,0.000000,3000000.0,USD
171,games_video,2008,MechaWorks,0.0,$0,37.383444,-122.009405,0.0,0
172,games_video,2008,Rev Media,0.0,$0,0.000000,0.000000,0.0,0
173,games_video,2008,Fictionaut,2.0,$0,40.759795,-73.916127,0.0,0
174,games_video,2009,Tiny Speck,45.0,$17.2M,49.282455,-123.109217,1500000.0,USD

In [10]:
clean_companies.to_json('clean_companies.json',orient='records')